version: '3'
services:
    nginx:
        container_name: nginx-lara
        depends_on:
            - lara
        build:
            context: docker-compose/nginx
            dockerfile: Dockerfile.nginx.dev
        restart: always
        ports:
            - '3000:80'
    db:
        image: postgres
        restart: always
        ports:
            - '5432:5432'
        environment:
            POSTGRES_PASSWORD: test123
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
    lara:
        container_name: lara
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/var/www
        environment:
            - TZ=Europe/Moscow
